name: Build

on:
  push:
    branches: [ main, experimental ]
  pull_request:
    branches: [ main, experimental ]
  workflow_dispatch:

jobs:
  buildWindows64:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4.1.7

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4

      - name: Set up Haxelib and run setup script
        run: |
          haxelib setup C:/haxelib
          haxelib install hxcpp > /dev/null --quiet
          .\"setup/Setup/setup-windows.bat"
        shell: cmd

      - name: Clone SScript Archive and install SScript.zip
        run: |
          git clone https://github.com/CCobaltDev/SScript-Archive.git
          haxelib install SScript-Archive/archives/SScript-7,7,0.zip
        shell: cmd

      - name: Skip SScript setup mode
        run: echo 'oy9:showMacroty8:loopCosti25y10:includeAllfg' >> %USERPROFILE%/settings.cocoa
        shell: cmd

      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION

      - name: Build (Windows 64-bit)
        run: haxelib run lime build windows --app-version="4.0.0-${{ github.run_id}}" -D officialBuild

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.4
        with:
          name: windowsBuild
          path: export/release/windows/bin

  buildWindows32:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4.1.7

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4

      - name: Set up Haxelib and run setup script
        run: |
          haxelib setup C:/haxelib
          haxelib install hxcpp > /dev/null --quiet
          .\"setup/Setup/setup-windows.bat"
        shell: cmd

      - name: Clone SScript Archive and install SScript.zip
        run: |
          git clone https://github.com/CCobaltDev/SScript-Archive.git
          haxelib install SScript-Archive/archives/SScript-7,7,0.zip
        shell: cmd

      - name: Skip SScript setup mode
        run: echo 'oy9:showMacroty8:loopCosti25y10:includeAllfg' >> %USERPROFILE%/settings.cocoa
        shell: cmd

      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION

      - name: Build (Windows 32-bit)
        run: haxelib run lime build windows -32 -release -D 32bits -D HXCPP_M32 --app-version="4.0.0-${{ github.run_id}}" -D officialBuild

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.4
        with:
          name: windowsBuild
          path: export/release/windows/bin
